# Generated by Django 6.1 on 2026-08-30 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualTryOnSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("completed", "Completada"),
                            ("abandoned", "Abandonada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "ai_model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="catalog.aimodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión del probador",
                "verbose_name_plural": "Sesiones del probador",
                "db_table": "virtual_tryon_sessions",
            },
        ),
        migrations.CreateModel(
            name="TryOnResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("avg_landmark_confidence", models.FloatField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tryon_results",
                        to="catalog.lashproduct",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="tryon_sessions.virtualtryonsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de prueba",
                "verbose_name_plural": "Resultados de prueba",
                "db_table": "tryon_results",
            },
        ),
        migrations.AddIndex(
            model_name="virtualtryonsession",
            index=models.Index(
                fields=["user_id", "started_at"], name="idx_session_user_started"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonresult",
            index=models.Index(fields=["session"], name="idx_result_session"),
        ),
        migrations.AddIndex(
            model_name="tryonresult",
            index=models.Index(
                fields=["product", "applied_at"], name="idx_result_product_applied"
            ),
        ),
    ]
