# Generated by Django 6.1 on 2026-08-30 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Modelo de IA",
                "verbose_name_plural": "Modelos de IA",
                "db_table": "ai_models",
            },
        ),
        migrations.CreateModel(
            name="LashProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("natural", "Natural"),
                            ("volumen", "Volumen"),
                            ("dramatico", "Dramático"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto de pestañas",
                "verbose_name_plural": "Productos de pestañas",
                "db_table": "lash_products",
            },
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_label", models.CharField(max_length=60)),
                ("model_asset_url", models.URLField(blank=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Versión que usan los LashAsset nuevos por defecto si no se especifica otra.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="catalog.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de modelo de IA",
                "verbose_name_plural": "Versiones de modelo de IA",
                "db_table": "ai_model_versions",
            },
        ),
        migrations.CreateModel(
            name="LashAsset",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="asset",
                        serialize=False,
                        to="catalog.lashproduct",
                    ),
                ),
                ("overlay_url", models.URLField()),
                ("canvas_width", models.PositiveIntegerField()),
                ("canvas_height", models.PositiveIntegerField()),
                ("anchor_inner_x", models.FloatField()),
                ("anchor_inner_y", models.FloatField()),
                ("anchor_outer_x", models.FloatField()),
                ("anchor_outer_y", models.FloatField()),
                ("eye_width_ref_px", models.FloatField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset de pestañas (AR)",
                "verbose_name_plural": "Assets de pestañas (AR)",
                "db_table": "lash_assets",
            },
        ),
        migrations.AddIndex(
            model_name="lashproduct",
            index=models.Index(
                fields=["active", "style"], name="idx_lashprod_active_style"
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodelversion",
            constraint=models.UniqueConstraint(
                fields=("ai_model", "version_label"), name="uniq_aimodel_version_label"
            ),
        ),
        migrations.AddField(
            model_name="lashasset",
            name="ai_model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lash_assets",
                to="catalog.aimodelversion",
            ),
        ),
    ]
